# Generated by Django 3.1.5 on 2021-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_auto_20210301_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="modoom",
            name="custom_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
