# Generated by Django 3.1.5 on 2021-03-01 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("emailed", models.BooleanField(db_index=True, default=False)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            (
                                "[모둠] 회원님의 모둠에 새로운 가입 신청이 도착했습니다. 📝",
                                "Modoom Request Received",
                            ),
                            (
                                "[모둠] 회원님의 모둠 가입 신청이 수락되었습니다. 😆",
                                "Modoom Request Accepted",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            (
                                "notifications/modoom_request_received.html",
                                "Modoom Request Received",
                            ),
                            (
                                "notifications/modoom_request_accepted.html",
                                "Modoom Request Accepted",
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("listed", models.BooleanField(db_index=True, default=False)),
                ("unread", models.BooleanField(db_index=True, default=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("님이 회원님의 모둠에 댓글을 남겼습니다.", "Modoom Comment"),
                            ("님이 회원님의 댓글에 답글을 남겼습니다.", "Comment Subcomment"),
                            ("님이 회원님의 모둠 가입을 거절했습니다.", "Modoom Request Declined"),
                            ("님이 회원님을 모둠에서 강퇴했습니다.", "Modoom Kicked"),
                            ("님이 회원님의 모둠 가입을 수락했습니다.", "Modoom Request Accepted"),
                            ("님이 회원님의 모둠 가입을 신청했습니다.", "Modoom Request Received"),
                            ("님이 회원님의 모둠에 가입했습니다.", "Modoom New Member"),
                            ("님이 회원님의 모둠에서 나갔습니다.", "Modoom Out Member"),
                            ("님이 회원님의 모둠을 종료했습니다.", "Modoom Closed"),
                            ("함께한 모둠원의 롤링페이퍼에 한마디를 작성해주세요!", "Review Write"),
                            ("모둠원이 회원님의 롤링페이퍼에 한마디를 작성했습니다!", "Review Received"),
                            ("님이 회원님의 친구 신청을 수락했습니다.", "Friend Request Accepted"),
                            ("님이 회원님에게 친구 신청을 보냈습니다.", "Friend Request Received"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("modoom", "Modoom"),
                            ("chat", "Chat"),
                            ("review_write", "Review Write"),
                            ("review_received", "Review Received"),
                            ("profile", "Profile"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
