# Generated by Django 3.1.5 on 2021-03-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_auto_20210305_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(
                choices=[
                    ("[모둠] 마음 맞는 사람들과 함께하는 곳, 모둠에 오신 것을 환영합니다.", "User Welcome"),
                    ("[모둠] 회원탈퇴 안내메일입니다.", "User Goodbye"),
                    ("[모둠] 회원님의 모둠에 새로운 가입 신청이 도착했습니다.", "Modoom Request Received"),
                    ("[모둠] 회원님의 모둠 가입 신청이 수락되었습니다.", "Modoom Request Accepted"),
                ],
                max_length=255,
            ),
        ),
    ]
