# Generated by Django 3.1.5 on 2021-03-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_reset_code"),
        ("notifications", "0004_auto_20210305_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="users.profile",
            ),
        ),
    ]
