# Generated by Django 3.1.5 on 2021-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("n_keywords", models.PositiveIntegerField(default=0)),
                ("n_profiles", models.PositiveIntegerField(default=0)),
                ("n_modooms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="keyword",
            name="keyword_group",
            field=models.ManyToManyField(
                blank=True, related_name="keywords", to="keywords.KeywordGroup"
            ),
        ),
    ]
