# Generated by Django 3.1.5 on 2021-03-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeds", "0001_initial"),
        ("chats", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modoommessage",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="modoomchatroomstatus",
            name="chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="chats.modoomchatroom",
            ),
        ),
        migrations.AddField(
            model_name="modoomchatroomstatus",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modoomchatroomstatus",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="modoomchatroom",
            name="modoom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="feeds.modoom",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chats.directchatroom",
            ),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="directchatroomstatus",
            name="chat_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="chats.directchatroom",
            ),
        ),
        migrations.AddField(
            model_name="directchatroomstatus",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directchatroomstatus",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="directchatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="direct_chat_rooms", to="users.Profile"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modoommessage",
            unique_together={("chat_room", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="modoomchatroomstatus",
            unique_together={("chat_room", "recipient")},
        ),
        migrations.AlterUniqueTogether(
            name="directmessage",
            unique_together={("chat_room", "position")},
        ),
        migrations.AlterUniqueTogether(
            name="directchatroomstatus",
            unique_together={("chat_room", "recipient")},
        ),
    ]
