# Generated by Django 3.1.5 on 2021-03-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_reset_code"),
        ("chats", "0002_auto_20210301_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directmessage",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="modoommessage",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modoommessage",
                to="users.profile",
            ),
        ),
    ]
