# Generated by Django 3.1.5 on 2021-03-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_auto_20210306_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="directchatroom",
            name="last_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="directchatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="modoomchatroom",
            name="last_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modoomchatroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
