# Generated by Django 3.1.5 on 2021-03-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeds", "0002_auto_20210301_1747"),
        ("users", "0001_initial"),
        ("relationships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_review",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_review",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="modoomship",
            name="modoom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationship",
                to="feeds.modoom",
            ),
        ),
        migrations.AddField(
            model_name="modoomship",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_modoomship",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="modoomship",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modoomship",
                to="relationships.review",
            ),
        ),
        migrations.AddField(
            model_name="modoomship",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_modoomship",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friendship",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friendship",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friendrequest",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friendrequest",
                to="users.profile",
            ),
        ),
    ]
