# Generated by Django 3.1.5 on 2021-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_code",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
