# Generated by Django 3.1.5 on 2021-03-06 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_reset_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pref_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                validators=[django.core.validators.EmailValidator("잘못된 이메일 형식입니다.")],
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_enroll_mails",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="receive_news_mails",
            field=models.BooleanField(default=True),
        ),
    ]
