# Generated by Django 3.1.5 on 2021-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210306_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="major",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
