# Generated by Django 3.1.5 on 2021-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_major"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="major",
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_info",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
